/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author JuanEduardo
 */
public class Catalogo extends javax.swing.JDialog {

    /**
     * Creates new form Catalogo
     * @param parent
     * @param modal
     */
    public Catalogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JPanel getPanel() {
        return Panel;
    }
    public JTextField getTxt_CostoPorDia() {
        return Txt_CostoPorDia;
    }

    public JTextField getTxt_PeliculasDisponibles() {
        return Txt_PeliculasDisponibles;
    }

    public JButton getBtn_CerrarCatalogo() {
        return Btn_CerrarCatalogo;
    }

    public JButton getBtn_EliminaCantidadPeliculas() {
        return Btn_EliminaCantidadPeliculas;
    }

    public JButton getBtn_AgregarPelicula() {
        return Btn_AgregarPelicula;
    }

    public JTextField getTxt_AgregarPelicula() {
        return Txt_AgregarPelicula;
    }

    public JButton getBtn_LimpiarDatosCatalogo() {
        return Btn_LimpiarDatosCatalogo;
    }

    public JTable getTablaCatalogo() {
        return TablaCatalogo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAgregarNueva_Pelicula = new javax.swing.JButton();
        Btn_ActualizarPelicula = new javax.swing.JButton();
        Btn_EliminarPelicula = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtID_Pelicula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre_Pelicula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtClasificacion_Pelicula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtIDSocio_Pelicula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_CostoPorDia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_PeliculasDisponibles = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCatalogo = new javax.swing.JTable();
        Btn_CerrarCatalogo = new javax.swing.JButton();
        Btn_LimpiarDatosCatalogo = new javax.swing.JButton();
        Txt_AgregarPelicula = new javax.swing.JTextField();
        Btn_AgregarPelicula = new javax.swing.JButton();
        Btn_EliminaCantidadPeliculas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BtnAgregarNueva_Pelicula.setText("Agregar");

        Btn_ActualizarPelicula.setText("Actualizar");

        Btn_EliminarPelicula.setText("Eliminar");

        jLabel1.setText("ID");

        jLabel2.setText("Título");

        jLabel3.setText("Clasificación");

        jLabel4.setText("ID Socio");

        jLabel5.setText("Costo por día");

        jLabel6.setText("Disponibles");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("$");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtNombre_Pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(TxtID_Pelicula)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_PeliculasDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(Txt_CostoPorDia)
                            .addComponent(TxtClasificacion_Pelicula)
                            .addComponent(TxtIDSocio_Pelicula))))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtID_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtClasificacion_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_CostoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Txt_PeliculasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDSocio_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        TablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                null
            }
        ));
        TablaCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCatalogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCatalogo);

        Btn_CerrarCatalogo.setText("Cerrar");

        Btn_LimpiarDatosCatalogo.setText("Limpiar");

        Btn_AgregarPelicula.setText("Agregar");

        Btn_EliminaCantidadPeliculas.setText("Quitar");

        jLabel8.setText("Para agregar o disminuir el inventario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Btn_LimpiarDatosCatalogo)
                                            .addComponent(BtnAgregarNueva_Pelicula)
                                            .addComponent(Btn_ActualizarPelicula)
                                            .addComponent(Btn_EliminarPelicula)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(Txt_AgregarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(Btn_AgregarPelicula)
                                        .addGap(28, 28, 28)
                                        .addComponent(Btn_EliminaCantidadPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Btn_CerrarCatalogo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(BtnAgregarNueva_Pelicula)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_ActualizarPelicula)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_EliminarPelicula)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_LimpiarDatosCatalogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_AgregarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_AgregarPelicula)
                            .addComponent(Btn_EliminaCantidadPeliculas))
                        .addGap(14, 14, 14)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(Btn_CerrarCatalogo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void TablaCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCatalogoMouseClicked
        
    }//GEN-LAST:event_TablaCatalogoMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Catalogo dialog = new Catalogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnAgregarNueva_Pelicula() {
        return BtnAgregarNueva_Pelicula;
    }

    public JTextField getTxtClasificacion_Pelicula() {
        return TxtClasificacion_Pelicula;
    }

    public JTextField getTxtIDSocio_Pelicula() {
        return TxtIDSocio_Pelicula;
    }

    public JTextField getTxtID_Pelicula() {
        return TxtID_Pelicula;
    }

    public JTextField getTxtNombre_Pelicula() {
        return TxtNombre_Pelicula;
    }

    public JButton getBtn_ActualizarPelicula() {
        return Btn_ActualizarPelicula;
    }

    public JButton getBtn_EliminarPelicula() {
        return Btn_EliminarPelicula;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarNueva_Pelicula;
    private javax.swing.JButton Btn_ActualizarPelicula;
    private javax.swing.JButton Btn_AgregarPelicula;
    private javax.swing.JButton Btn_CerrarCatalogo;
    private javax.swing.JButton Btn_EliminaCantidadPeliculas;
    private javax.swing.JButton Btn_EliminarPelicula;
    private javax.swing.JButton Btn_LimpiarDatosCatalogo;
    private javax.swing.JPanel Panel;
    private javax.swing.JTable TablaCatalogo;
    private javax.swing.JTextField TxtClasificacion_Pelicula;
    private javax.swing.JTextField TxtIDSocio_Pelicula;
    private javax.swing.JTextField TxtID_Pelicula;
    private javax.swing.JTextField TxtNombre_Pelicula;
    private javax.swing.JTextField Txt_AgregarPelicula;
    private javax.swing.JTextField Txt_CostoPorDia;
    private javax.swing.JTextField Txt_PeliculasDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
