/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import javax.swing.JButton;

/**
 *
 * @author SEARS
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
  
    }

    public JButton getBtn_ReportesCon() {
        return Btn_ReportesCon;
    }

    public JButton getBtn_CerrarVentanaPrincipal() {
        return Btn_CerrarVentanaPrincipal;
    }

    public JButton getBtn_RegistroDevolución() {
        return btn_RegistroDevolución;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCatalogo = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnSocios = new javax.swing.JButton();
        Btn_Registro = new javax.swing.JButton();
        btn_RegistroDevolución = new javax.swing.JButton();
        Btn_CerrarVentanaPrincipal = new javax.swing.JButton();
        Btn_ReportesCon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnCatalogo.setText("Catalogo");
        btnCatalogo.setFocusable(false);
        btnCatalogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCatalogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCatalogo);

        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnClientes);

        btnSocios.setText("Socios");
        btnSocios.setFocusable(false);
        btnSocios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSocios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSocios);

        Btn_Registro.setText("Registro venta");
        Btn_Registro.setFocusable(false);
        Btn_Registro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Registro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Btn_Registro);

        btn_RegistroDevolución.setText("Registro devolucion");
        btn_RegistroDevolución.setFocusable(false);
        btn_RegistroDevolución.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_RegistroDevolución.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_RegistroDevolución);

        Btn_CerrarVentanaPrincipal.setText("Cerrar");

        Btn_ReportesCon.setText("ReportesCon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_CerrarVentanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_ReportesCon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Btn_ReportesCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(Btn_CerrarVentanaPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    public JButton getBtnCatalogo() {
        return btnCatalogo;
    }

    public JButton getBtnClientes() {
        return btnClientes;
    }

    public JButton getBtn_Registro() {
        return Btn_Registro;
    }

    public JButton getBtnSocios() {
        return btnSocios;
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CerrarVentanaPrincipal;
    private javax.swing.JButton Btn_Registro;
    private javax.swing.JButton Btn_ReportesCon;
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnSocios;
    private javax.swing.JButton btn_RegistroDevolución;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
