/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuanEduardo
 */
public class GFrame extends javax.swing.JFrame {

    /**
     * Creates new form GFrame
     */
    public GFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escolaridad = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaOrigen = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaDestino = new javax.swing.JTextArea();
        TxtCopiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        OpciónKinder = new javax.swing.JRadioButton();
        OpcionPrimaria = new javax.swing.JRadioButton();
        OpcionSecundaria = new javax.swing.JRadioButton();
        BotonObtener = new javax.swing.JButton();
        TxtRespuesta = new javax.swing.JTextField();
        Hermosa = new javax.swing.JCheckBox();
        Inteligente = new javax.swing.JCheckBox();
        Atletica = new javax.swing.JCheckBox();
        Feliz = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        TxtMostrar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtAreaOrigen.setColumns(20);
        TxtAreaOrigen.setRows(5);
        jScrollPane1.setViewportView(TxtAreaOrigen);

        TxtAreaDestino.setEditable(false);
        TxtAreaDestino.setColumns(20);
        TxtAreaDestino.setRows(5);
        jScrollPane2.setViewportView(TxtAreaDestino);

        TxtCopiar.setText("Copiar>>>");
        TxtCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCopiarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        Escolaridad.add(OpciónKinder);
        OpciónKinder.setText("Kinder");
        OpciónKinder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpciónKinderItemStateChanged(evt);
            }
        });

        Escolaridad.add(OpcionPrimaria);
        OpcionPrimaria.setText("Primaria");
        OpcionPrimaria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpcionPrimariaItemStateChanged(evt);
            }
        });

        Escolaridad.add(OpcionSecundaria);
        OpcionSecundaria.setText("Secundaria");
        OpcionSecundaria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpcionSecundariaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OpcionSecundaria)
                    .addComponent(OpciónKinder, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpcionPrimaria, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(OpciónKinder)
                .addGap(18, 18, 18)
                .addComponent(OpcionPrimaria)
                .addGap(18, 18, 18)
                .addComponent(OpcionSecundaria)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        BotonObtener.setText("Obtener");
        BotonObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonObtenerActionPerformed(evt);
            }
        });

        Hermosa.setText("Hermosa");

        Inteligente.setText("Inteligente");

        Atletica.setText("Atletica");

        Feliz.setText("Feliz");

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(TxtCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonObtener)
                .addGap(18, 18, 18)
                .addComponent(TxtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Atletica)
                    .addComponent(Inteligente)
                    .addComponent(Hermosa)
                    .addComponent(Feliz)
                    .addComponent(jButton1))
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(TxtCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonObtener)
                            .addComponent(TxtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Hermosa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Inteligente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Atletica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Feliz)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(TxtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCopiarActionPerformed
        TxtAreaDestino.setText(TxtAreaOrigen.getSelectedText());
    }//GEN-LAST:event_TxtCopiarActionPerformed

    private void OpciónKinderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpciónKinderItemStateChanged
        System.out.println(evt.getItem());
        TxtRespuesta.setText("Kinder");
        
    }//GEN-LAST:event_OpciónKinderItemStateChanged

    private void OpcionPrimariaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpcionPrimariaItemStateChanged
        TxtRespuesta.setText("Primaria");
    }//GEN-LAST:event_OpcionPrimariaItemStateChanged

    private void OpcionSecundariaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpcionSecundariaItemStateChanged
        TxtRespuesta.setText("Secundaria");
    }//GEN-LAST:event_OpcionSecundariaItemStateChanged

    private void BotonObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonObtenerActionPerformed
        if(OpciónKinder.isSelected()==true){
        TxtRespuesta.setText("Kinder");
        }
        if(OpcionPrimaria.isSelected()==true){
        TxtRespuesta.setText("Primaria");
        }
        if(OpcionSecundaria.isSelected()==true){
        TxtRespuesta.setText("Secundaria");
        }
    }//GEN-LAST:event_BotonObtenerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a="Eres ";
        if(Hermosa.isSelected()==true){
        a+="Hermosa ";
        }
        if(Inteligente.isSelected()==true){
            a+="Inteligente ";
        }
        if(Atletica.isSelected()==true){
            a+="Atletica ";
        }
        if(Feliz.isSelected()==true){
            a+="Feliz ";
        }
        if(a.length()==40)
        TxtMostrar.setText("Eres la mujer ideal");
        
        else
        TxtMostrar.setText(a);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Atletica;
    private javax.swing.JButton BotonObtener;
    private javax.swing.ButtonGroup Escolaridad;
    private javax.swing.JCheckBox Feliz;
    private javax.swing.JCheckBox Hermosa;
    private javax.swing.JCheckBox Inteligente;
    private javax.swing.JRadioButton OpcionPrimaria;
    private javax.swing.JRadioButton OpcionSecundaria;
    private javax.swing.JRadioButton OpciónKinder;
    private javax.swing.JTextArea TxtAreaDestino;
    private javax.swing.JTextArea TxtAreaOrigen;
    private javax.swing.JButton TxtCopiar;
    private javax.swing.JTextField TxtMostrar;
    private javax.swing.JTextField TxtRespuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
